In [36]:
import numpy as np

In [37]:
#Recap
arr = np.array([[1,2,3],[4,5,6]])

In [38]:
type(arr)

numpy.ndarray

In [75]:
#Dot product-m x n||n x p
arr1= np. random.randint(1,2,(3,1))

In [76]:
arr1.shape
arr1. shape

(3, 1)

In [77]:
arr. size

6

In [78]:
result = np.dot(arr,arr1)

In [79]:
print(result)

[[ 6]
 [15]]


In [56]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[10 13 14]
 [17 15 17]
 [14 10 11]]


In [57]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
# r1 . I
result2 = np.dot(r2,r1)

In [59]:
print(result2)

[[10. 13. 14.]
 [17. 15. 17.]
 [14. 10. 11.]]


In [60]:
#.M.I.=.I M.=.M

In [61]:
#.A.B.!=.B•.•A

In [62]:
# Mathematical Operations
# + - * /
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(2,6,(3,3))

In [63]:
print(t1)
print(t2)

[[5 4 3]
 [3 3 3]
 [5 4 4]]
[[4 4 5]
 [4 3 5]
 [5 3 5]]


In [64]:
t3 = t1 + t2

In [65]:
print(t3)

[[ 9  8  8]
 [ 7  6  8]
 [10  7  9]]


In [80]:
# Matrix multiplication
result = np.dot(arr,arr1)

In [82]:
# Statistical operations
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [83]:
print(mean)
print(max)
print(median)
print(std)
print(var)

8.0
10
8.0
1.1547005383792515
1.3333333333333333


In [84]:
std * std

1.3333333333333333

In [85]:

# Trignometric functions
# sin(x)
# cos(x)
# Tan(x) - sin(x) / cos(x)
# cosec -
# sec - 1 / cos(x)
# cot - 1 / tan(x)
angles = np.array([0,15,30,45,60,75,90])
result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [86]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [87]:
arr = np.array([[1,1,2,4,5,6]])
# Reshpa the array
reshapedarr = arr.reshape(3,2)
print(reshapedarr)
# Convert / arr.flatten any n dim array
flattendarr = arr.flatten()
print(flattendarr)

[[1 1]
 [2 4]
 [5 6]]
[1 1 2 4 5 6]


In [88]:
# Stacking the data
arr1 = np.array([[1,2,3,4],[2,3,4,5]])
arr2 = np.array([10,20,30,40])

arr3 = np.vstack((arr1,arr2))
print(f'The shape of arr3 is {arr3.shape}')

# Horizantal Stacking
arr4 = np.hstack((arr1,arr2.reshape(2,2)))
print(f'The shape of arr4 is {arr4.shape}')
print(arr4)

The shape of arr3 is (3, 4)
The shape of arr4 is (2, 6)
[[ 1  2  3  4 10 20]
 [ 2  3  4  5 30 40]]


In [89]:
# Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr [arr > 40]

print(farr)

[50 60 70 80]
